name: bulk_insert_deploy_commit
on:
  workflow_dispatch:
  pull_request:
      types:
        - closed
      branches:
        - main

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bulk insert deploy pull request.
        run: ./.github/workflows/deploy_frequency.sh
        env:
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
          SPREAD_SHEET_URL: ${{ secrets.SPREAD_SHEET_URL }}
        shell: bash
